/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AuditLogTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SocialBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SocialChatTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}

import "sst"
export {}